name: Creative Effects
favicon: null
layout_spectrum: 0.4019243132788688
typography_spectrum: 0.47878
title: Creative Effects Advertising Design Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5135b2'
    - '#dfc264'
    - '#ee7800'
    - '#9d8dd4'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
