name: Creative Effects
favicon: null
layout_spectrum: 0.4019243132788688
typography_spectrum: 0.56717
title: Creative Effects Advertising Design Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5135b2'
    - '#dfc264'
    - '#ee7800'
    - '#9d8dd4'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.43933956511318684
purpose: []
